import Head from "next/head";
import React, { useEffect } from "react";
import { AppProvider } from "../context";
import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";
gsap.registerPlugin(ScrollTrigger);

import Navbar from "@/ui/Navbar";
import Footer from "@/ui/Footer";

export default function Home() {
  useEffect(() => {
    // let tl1 = gsap.timeline({
    //   scrollTrigger: {
    //     trigger: ".home-services-body",
    //     start: "top 75%",
    //   },
    // });
    // tl1.to(".home-services-body .desc", {
    //   opacity: 1,
    //   duration: 1,
    //   ease: "power4.out",
    // });
    gsap.to(".hero-wrapper", {
      opacity: 1,
      duration: 2,
    });
  }, []);
  return (
    <AppProvider>
      <Head>
        <title>Roomie</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="home-body relative">
        <Navbar />
        <div className="relative opacity-0 hero-wrapper box-border overflow-x-hidden flex justify-between min-w-[100vw] min-h-[100vh] items-center sm:px-[5vw]">
          <div className="w-3/5">
            <h1 className="text-[3.75rem] font-bold pb-[0.5em] leading-[1.1]">
              Come and Find your perfect shared living space.
            </h1>
            <div className="flex items-start justify-between pt-[2em]">
              <p className="pb-[0.5em]">
                Experience the comfort of a hassle-free room search and matching
                process with us and find an ideal living experience anywhere in
                the world.
              </p>
              <div className="btn-wrapper w-full flex justify-items-end pr-[2em] ml-[3rem]">
                <button className="cursor-pointer py-[1em] px-[2.5em] rounded bg-[#FEF3A1] shadow-2xl font-medium hover:bg-[#FFE395]">
                  Find room/roommates
                </button>
                {/* <button className="ml-[4em] cursor-pointer py-[1em] px-[2.5em] rounded bg-[#FEF3D3] shadow-2xl font-medium hover:bg-[#FFE395]">
                Find room mates
              </button> */}
              </div>
            </div>
          </div>
          {/* translate-y-[20vh] */}
          <div className="img-wrapper absolute right-[5vw] w-[36%] mt-[10vh] ">
            <img
              className="w-11/12"
              src="/hero-img-3.png"
              alt="house and roommate image"
            ></img>
          </div>
        </div>
        <section className="mt-[3em] px-[5vw] pb-[10vh]">
          <h2 className="text-4xl font-medium">What we provide . . .</h2>

          <div className="services-wrapper flex justify-between">
            <div className="card mt-[25vh] max-w-[25vw] bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
              <div className="flex flex-col items-center pb-10 relative">
                <div className="h-[150px] w-[150px] absolute top-[-50px] ">
                  <img src="/service-1-1.png" alt="service-1" />
                </div>
                <h4 className="mb-1 mt-[4.5em] text-2xl font-semibold text-gray-900 dark:text-white">
                  Find Rooms
                </h4>
                <span className="text-sm text-gray-500 dark:text-gray-400 px-[3em] mt-[1em]">
                  Find rooms that best suite your needs and comfort at the palm
                  of your hand
                </span>
                <div className="flex mt-4 space-x-3 md:mt-6">
                  <a
                    href="#"
                    className="inline-flex items-center px-4 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-md hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
                  >
                    Explore
                  </a>
                </div>
              </div>
            </div>
            <div className="card mt-[25vh] max-w-[25vw] bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
              <div className="flex flex-col items-center pb-10 relative">
                <div className="max-h-[150px] w-[150px] absolute top-[-50px]">
                  <img src="/service-1.png" alt="service-1" />
                </div>
                <h4 className="mb-1 mt-[4.5em] text-2xl font-semibold text-gray-900 dark:text-white">
                  Find Roommates
                </h4>
                <span className="text-sm text-gray-500 dark:text-gray-400 px-[3em] mt-[1em]">
                  Easily find the roommate that best matches with your interests
                  in any locality of choice
                </span>
                <div className="flex mt-4 space-x-3 md:mt-6">
                  <a
                    href="#"
                    className="inline-flex items-center px-4 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-md hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
                  >
                    Explore
                  </a>
                </div>
              </div>
            </div>
            <div className="card mt-[25vh] max-w-[25vw]  bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
              <div className="flex flex-col items-center pb-10 relative">
                <div className="max-h-[150px] w-[150px] absolute top-[-50px]">
                  <img src="/service-3.png" alt="service-1" />
                </div>
                <h4 className="mb-1 mt-[4.5em] text-2xl font-semibold text-gray-900 dark:text-white">
                  An ideal combination
                </h4>
                <span className="text-sm text-gray-500 dark:text-gray-400 px-[3em] mt-[1em]">
                  Use various filters and narrow it down to the best combination
                  of rooms and room mates
                </span>
                <div className="flex mt-4 space-x-3 md:mt-6">
                  <a
                    href="#"
                    className="inline-flex items-center px-4 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-md hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
                  >
                    Explore
                  </a>
                </div>
              </div>
            </div>
          </div>
        </section>
        <Footer />
      </div>
    </AppProvider>
  );
}
